/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Gabriel
 */
public class alterarProduto2 extends javax.swing.JFrame {

    /**
     * Creates new form alterarProduto2
     */
    public alterarProduto2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProduto = new javax.swing.JLabel();
        lblUnitario = new javax.swing.JLabel();
        lblFornecedor = new javax.swing.JLabel();
        lblEstoque = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        txtUnitario = new javax.swing.JTextField();
        txtFornecedor = new javax.swing.JTextField();
        txtEstoque = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        mnuRelatorio = new javax.swing.JMenu();
        mnuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblProduto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblProduto.setForeground(new java.awt.Color(255, 255, 255));
        lblProduto.setText("PRODUTO");
        getContentPane().add(lblProduto);
        lblProduto.setBounds(70, 40, 130, 40);

        lblUnitario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUnitario.setForeground(new java.awt.Color(255, 255, 255));
        lblUnitario.setText("TPUNITARIO");
        getContentPane().add(lblUnitario);
        lblUnitario.setBounds(70, 90, 130, 40);

        lblFornecedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        lblFornecedor.setText("FORNECEDOR");
        getContentPane().add(lblFornecedor);
        lblFornecedor.setBounds(70, 140, 130, 40);

        lblEstoque.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEstoque.setForeground(new java.awt.Color(255, 255, 255));
        lblEstoque.setText("ESTOQUEAT");
        getContentPane().add(lblEstoque);
        lblEstoque.setBounds(70, 190, 130, 40);
        getContentPane().add(txtProduto);
        txtProduto.setBounds(200, 40, 310, 40);
        getContentPane().add(txtUnitario);
        txtUnitario.setBounds(200, 90, 310, 40);

        txtFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(txtFornecedor);
        txtFornecedor.setBounds(200, 140, 310, 40);
        getContentPane().add(txtEstoque);
        txtEstoque.setBounds(200, 190, 310, 40);

        btnAlterar.setBackground(new java.awt.Color(204, 153, 0));
        btnAlterar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("ALTERAR");
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(210, 250, 140, 50);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(50, 40, 150, 40);

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(50, 90, 150, 40);

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));
        jPanel4.setLayout(null);
        jPanel1.add(jPanel4);
        jPanel4.setBounds(50, 140, 150, 40);

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);
        jPanel1.add(jPanel5);
        jPanel5.setBounds(50, 190, 150, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 350);

        mnuInicio.setText("INÍCIO  |");
        jMenuBar1.add(mnuInicio);

        mnuRelatorio.setText("RELATÓRIO  |");
        jMenuBar1.add(mnuRelatorio);

        mnuAjuda.setText("AJUDA  |");
        jMenuBar1.add(mnuAjuda);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(616, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alterarProduto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alterarProduto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alterarProduto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alterarProduto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alterarProduto2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblUnitario;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuInicio;
    private javax.swing.JMenu mnuRelatorio;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtUnitario;
    // End of variables declaration//GEN-END:variables
}
