/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author guidi
 */
public class relatorio extends javax.swing.JFrame {

    /**
     * Creates new form relatorio
     */
    public relatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnMaisVendidos = new javax.swing.JButton();
        BtnMenosVendidos = new javax.swing.JButton();
        BtnMaiorEstoque = new javax.swing.JButton();
        BtnMenorEstoque = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnCadastrarTelaPrincipal = new javax.swing.JMenu();
        MnRelatorio = new javax.swing.JMenu();
        MnAjudaTelaPrincipal = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        BtnMaisVendidos.setBackground(new java.awt.Color(102, 102, 255));
        BtnMaisVendidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnMaisVendidos.setForeground(new java.awt.Color(255, 255, 255));
        BtnMaisVendidos.setText("Mais Vendidos");
        BtnMaisVendidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMaisVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMaisVendidosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMaisVendidos);
        BtnMaisVendidos.setBounds(190, 190, 210, 70);

        BtnMenosVendidos.setBackground(new java.awt.Color(102, 102, 255));
        BtnMenosVendidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnMenosVendidos.setForeground(new java.awt.Color(255, 255, 255));
        BtnMenosVendidos.setText("Menos Vendidos");
        BtnMenosVendidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMenosVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenosVendidosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMenosVendidos);
        BtnMenosVendidos.setBounds(190, 270, 210, 70);

        BtnMaiorEstoque.setBackground(new java.awt.Color(102, 102, 255));
        BtnMaiorEstoque.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnMaiorEstoque.setForeground(new java.awt.Color(255, 255, 255));
        BtnMaiorEstoque.setText("Maior Estoque");
        BtnMaiorEstoque.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMaiorEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMaiorEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMaiorEstoque);
        BtnMaiorEstoque.setBounds(190, 30, 210, 70);

        BtnMenorEstoque.setBackground(new java.awt.Color(102, 102, 255));
        BtnMenorEstoque.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnMenorEstoque.setForeground(new java.awt.Color(255, 255, 255));
        BtnMenorEstoque.setText("Menor Estoque");
        BtnMenorEstoque.setToolTipText("");
        BtnMenorEstoque.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnMenorEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenorEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMenorEstoque);
        BtnMenorEstoque.setBounds(190, 110, 210, 70);

        jMenuBar1.setBackground(new java.awt.Color(51, 102, 255));

        MnCadastrarTelaPrincipal.setText("Cadastro");
        jMenuBar1.add(MnCadastrarTelaPrincipal);

        MnRelatorio.setText("Relatorio");
        jMenuBar1.add(MnRelatorio);

        MnAjudaTelaPrincipal.setText("Ajuda");
        jMenuBar1.add(MnAjudaTelaPrincipal);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(616, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMaisVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMaisVendidosActionPerformed
        new relatorio2().setVisible(true);
    }//GEN-LAST:event_BtnMaisVendidosActionPerformed

    private void BtnMenosVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenosVendidosActionPerformed
        new relatorio2().setVisible(true);
    }//GEN-LAST:event_BtnMenosVendidosActionPerformed

    private void BtnMaiorEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMaiorEstoqueActionPerformed
        new relatorio2().setVisible(true);
    }//GEN-LAST:event_BtnMaiorEstoqueActionPerformed

    private void BtnMenorEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenorEstoqueActionPerformed
        new relatorio2().setVisible(true);
    }//GEN-LAST:event_BtnMenorEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMaiorEstoque;
    private javax.swing.JButton BtnMaisVendidos;
    private javax.swing.JButton BtnMenorEstoque;
    private javax.swing.JButton BtnMenosVendidos;
    private javax.swing.JMenu MnAjudaTelaPrincipal;
    private javax.swing.JMenu MnCadastrarTelaPrincipal;
    private javax.swing.JMenu MnRelatorio;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
